Myaxf/Myaxf/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('axf.urls', namespace='axf')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

Myaxf/axf/urls.py
from django.conf.urls import url

from axf import views








urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^market/', views.market, name='market'),
    url(r'^jsonmarket/', views.josn_market, name='jsonmarket'),
    url(r'^marketwidthparmas/(?P<categoryid>\d+)/(?P<childcid>\d+)/(?P<order_rule>\d+)/', views.market_width_parmas, name='marketwidthparmas'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^mine/', views.mine, name='mine'),
    url(r'^userregister/', views.user_register, name='userregister'),
    url(r'^userlogout/', views.user_logout, name='userlogout'),
    url(r'^checkuser/', views.check_user, name='checkuser'),
    url(r'^checkemal/', views.check_emal, name='checkemal'),
    url(r'^userlogin/', views.user_login, name='userlogin'),
    url(r'^addtocartinmarket/', views.add_to_cart_inmarket, name='addtocartinmarket'),
    url(r'^subtocartinmarket/', views.sub_to_cart_inmarket, name='subtocartinmarket'),
    url(r'^subtocart/', views.sub_to_cart, name='subtocart'),
    url(r'^addtocart/', views.add_to_cart, name='addtocart'),
    url(r'^changecartstatus/', views.change_cart_status, name='changecartstatus'),
    url(r'^changecartsstatus/', views.change_carts_status, name='changecartsstatus'),
    url(r'^makeorder/', views.make_order, name='makeorder'),
    url(r'^orderdetail/', views.order_detail, name='orderdetail'),
    url(r'^alipay/', views.alipay, name='alipay'),
    url(r'^activeuser/', views.active_user, name='activeuser'),
    url(r'^orderlist/', views.order_list, name='orderlist'),
    url(r'^changeorderstatus/', views.change_order_status, name='changeorderstatus'),

]

Myaxf/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    {% block extCSS %}
    
    {% endblock %}
</head>
<body>
    {% block header %}
        
    
    {% endblock %}
    
    {% block content %}
    
    {% endblock %}
    
    {% block footer %}
    
    {% endblock %}








    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/base.js' %}"></script>

    {% block extJS %}
    
    {% endblock %}
</body>
</html>

Myaxf/templates/base/base_main.html
{% extends 'base/base.html' %}
{% load static %}
{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/main.css' %}">
{% endblock %}

{% block header %}
    <header></header>
{% endblock %}

{% block footer %}
    <footer>
        <a href="{% url 'axf:home' %}" class="home">
            <dl>
                <dt>
                    <span></span>
                </dt>
            </dl>
            <dd>首页</dd>
        </a>
        <a href="{% url 'axf:market' %}" class="market">
            <dl>
                <dt>
                    <span></span>
                </dt>
            </dl>
            <dd>闪购</dd>
        </a>
        <a href="{% url 'axf:cart' %}" class="cart">
            <dl>
                <dt>
                    <span></span>
                </dt>
            </dl>
            <dd>购物车</dd>
        </a>
        <a href="{% url 'axf:mine' %}" class="mine">
            <dl>
                <dt>
                    <span></span>
                </dt>
            </dl>
            <dd>我的</dd>
        </a>
    </footer>
{% endblock %}

Myaxf/templates/base/base_order.html
{% extends 'base/base.html' %}

Myaxf/templates/base/base_user.html
{% extends 'base/base.html' %}
{% load static %}
{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/user/css/user.css' %}">

{% endblock %}

{% block extJS %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/md5.js' %}"></script>
{% endblock %}
{% block header %}
   <a href="{% url 'axf:mine'  %}">
    <header>返回</header>
    </a>
{% endblock %}