Myaxf/Myaxf/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('axf.urls', namespace='axf')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

Myaxf/axf/urls.py
from django.conf.urls import url

from axf import views








urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^market/', views.market, name='market'),
    url(r'^jsonmarket/', views.josn_market, name='jsonmarket'),
    url(r'^marketwidthparmas/(?P<categoryid>\d+)/(?P<childcid>\d+)/(?P<order_rule>\d+)/', views.market_width_parmas, name='marketwidthparmas'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^mine/', views.mine, name='mine'),
    url(r'^userregister/', views.user_register, name='userregister'),
    url(r'^userlogout/', views.user_logout, name='userlogout'),
    url(r'^checkuser/', views.check_user, name='checkuser'),
    url(r'^checkemal/', views.check_emal, name='checkemal'),
    url(r'^userlogin/', views.user_login, name='userlogin'),
    url(r'^addtocartinmarket/', views.add_to_cart_inmarket, name='addtocartinmarket'),
    url(r'^subtocartinmarket/', views.sub_to_cart_inmarket, name='subtocartinmarket'),
    url(r'^subtocart/', views.sub_to_cart, name='subtocart'),
    url(r'^addtocart/', views.add_to_cart, name='addtocart'),
    url(r'^changecartstatus/', views.change_cart_status, name='changecartstatus'),
    url(r'^changecartsstatus/', views.change_carts_status, name='changecartsstatus'),
    url(r'^makeorder/', views.make_order, name='makeorder'),
    url(r'^orderdetail/', views.order_detail, name='orderdetail'),
    url(r'^alipay/', views.alipay, name='alipay'),
    url(r'^activeuser/', views.active_user, name='activeuser'),
    url(r'^orderlist/', views.order_list, name='orderlist'),
    url(r'^changeorderstatus/', views.change_order_status, name='changeorderstatus'),

]

Myaxf/templates/mine/mine.html
{% extends 'base/base_main.html' %}
{% load static %}
{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/mine/css/mine.css' %}">
{% endblock %}
{% block extJS %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/mine/js/mine.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="mine">
        <div class="fixed">
            {% if is_login %}
                <span>
                <img src="{{ user_icon }}" alt="icon">
                </span>
            {% else %}
                <span class="glyphicon glyphicon-user"></span>

            {% endif %}
            {% if is_login %}
                <p>{{ username }}</p>
            {% else %}

                <p>
                    <a href="{% url 'axf:userlogin' %}" class="not_login">未登录</a>
                </p>
            {% endif %}

            <p class="level">
                <span class="glyphicon glyphicon-fire"></span>
                <span>等级</span>
            </p>
            {% if is_login %}
            {% else %}
                <div id="regis">
                    <a href="{% url 'axf:userregister' %}">注册</a>
                </div>
            {% endif %}

            <p class="collect">
                <span class="glyphicon glyphicon-heart"></span>
                <span>收藏</span>
            </p>

        </div>
        <div class="mine_info">
            <p>
                <span>我的订单</span>
                <a href="#">查看全部订单&gt;</a>
            </p>
            <nav id="nav">
                <ul>
                    <li>
                        <a href="{% url 'axf:orderlist' %}?status=0">
                            <dl>
                                <span class="count badge">{{ orderdcount }}</span>
                                <dt>
                                    <span class="glyphicon glyphicon-usd"></span>
                                </dt>
                                <dd>待付款</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'axf:orderlist' %}?status=1">
                            <dl>
                                <span class="count badge">{{ wait_receive_count }}</span>
                                <dt>
                                    <span class="glyphicon glyphicon-envelope"></span>
                                </dt>
                                <dd>待收货</dd>
                            </dl>
                        </a>
                    </li>

                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-pencil"></span>
                            </dt>
                            <dd>待评价</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-retweet"></span>
                            </dt>
                            <dd>退款/售后</dd>
                        </dl>
                    </li>
                </ul>
            </nav>
            <menu>
                <ul>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-bullhorn"></span>
                            </dt>
                            <dd>积分商城</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-credit-card"></span>
                            </dt>
                            <dd>优惠券</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-import"></span>
                            </dt>
                            <dd>收货地址</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-phone-alt"></span>
                            </dt>
                            <dd>客服/反馈</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-asterisk"></span>
                            </dt>
                            <dd>关于我们</dd>
                        </dl>
                    </li>
                </ul>
            </menu>
            {% if is_login %}
                <p>
                    <a href="{% url 'axf:userlogout' %}">退出登录</a>
                </p>
            {% endif %}

        </div>


    </div>
{% endblock %}