Myaxf/Myaxf/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('axf.urls', namespace='axf')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

Myaxf/axf/urls.py
from django.conf.urls import url

from axf import views








urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^market/', views.market, name='market'),
    url(r'^jsonmarket/', views.josn_market, name='jsonmarket'),
    url(r'^marketwidthparmas/(?P<categoryid>\d+)/(?P<childcid>\d+)/(?P<order_rule>\d+)/', views.market_width_parmas, name='marketwidthparmas'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^mine/', views.mine, name='mine'),
    url(r'^userregister/', views.user_register, name='userregister'),
    url(r'^userlogout/', views.user_logout, name='userlogout'),
    url(r'^checkuser/', views.check_user, name='checkuser'),
    url(r'^checkemal/', views.check_emal, name='checkemal'),
    url(r'^userlogin/', views.user_login, name='userlogin'),
    url(r'^addtocartinmarket/', views.add_to_cart_inmarket, name='addtocartinmarket'),
    url(r'^subtocartinmarket/', views.sub_to_cart_inmarket, name='subtocartinmarket'),
    url(r'^subtocart/', views.sub_to_cart, name='subtocart'),
    url(r'^addtocart/', views.add_to_cart, name='addtocart'),
    url(r'^changecartstatus/', views.change_cart_status, name='changecartstatus'),
    url(r'^changecartsstatus/', views.change_carts_status, name='changecartsstatus'),
    url(r'^makeorder/', views.make_order, name='makeorder'),
    url(r'^orderdetail/', views.order_detail, name='orderdetail'),
    url(r'^alipay/', views.alipay, name='alipay'),
    url(r'^activeuser/', views.active_user, name='activeuser'),
    url(r'^orderlist/', views.order_list, name='orderlist'),
    url(r'^changeorderstatus/', views.change_order_status, name='changeorderstatus'),

]

Myaxf/templates/market/market.html
{% extends 'base/base_main.html' %}
{% load static %}
{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/market/css/market.css' %}">
{% endblock %}

{% block extJS %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/market/js/market.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="market">
        <aside>
            <ul>
                {% for foodtype in foodtypes %}
                    <li>
                        <a href="{% url 'axf:marketwidthparmas' categoryid=foodtype.typeid childcid=0 order_rule=0 %}">{{ foodtype.typename }}</a>
                        {% ifequal foodtype.typeid categoryid %}
                            <span class="yellowSlide"></span>
                        {% endifequal %}

                    </li>
                {% endfor %}
            </ul>
        </aside>
        <section>

            <nav>
                <ul>
                    <li id="all_type">
                        <span>全部类型<span class="glyphicon glyphicon-chevron-down"></span></span>
                    </li>
                    <li id="sort_rule">
                        <span>综合排序<span class="glyphicon glyphicon-chevron-down"></span></span>
                    </li>
                </ul>
            </nav>
            <menu>
                <ul>
                    {% for goods in goodslist %}
                        <li>
                            <a href="#">
                                <img src="{{ goods.productimg }}" alt="{{ goods.productlongname }}">
                                <div class="shoppingInfo">
                                    <h6>{{ goods.productlongname }}</h6>
                                    <p class="detailTag"><span>精选</span><span></span></p>
                                    <p class="unit">{{ goods.specifics }}</p>
                                    <p class="price"><span>￥{{ goods.price }}</span><s>￥{{ goods.marketprice }}</s></p>
                                </div>


                            </a>
                            <section>
                                <button class="subShopping">－</button>
                                {% if islogin %}
                                    <span></span>
                                    {% else %}
                                    <span>0</span>
                                {% endif %}
                                <button class="addShopping" goodsid="{{ goods.id }}">＋</button>
                            </section>
                        </li>

                    {% endfor %}

                </ul>
                <div id="all_type_container">
                    <div>
                        {% for childtype in childtypelist %}
                            <a href="{% url 'axf:marketwidthparmas' categoryid=categoryid childcid=childtype.1 order_rule=order_rule %}">
                                {% ifequal childcid childtype.1 %}
                                    <button class="btn btn-default btn-success">{{ childtype.0 }}</button>
                                {% else %}
                                    <button class="btn btn-default">{{ childtype.0 }}</button>

                                {% endifequal %}


                            </a>
                        {% endfor %}
                    </div>
                </div>
                <div id="sort_rule_container">
                    <div>
                        <a href="{% url 'axf:marketwidthparmas' categoryid=categoryid childcid=childcid order_rule=0 %}">
                            {% ifequal order_rule '0' %}
                                <button class="btn btn-default btn-success">综合排序</button>
                            {% else %}
                                <button class="btn btn-default">综合排序</button>

                            {% endifequal %}

                        </a><a
                            href="{% url 'axf:marketwidthparmas' categoryid=categoryid childcid=childcid order_rule=1 %}">

                        {% ifequal order_rule '1' %}
                            <button class="btn btn-default btn-success">价格最低</button>
                        {% else %}
                            <button class="btn btn-default">价格最低</button>

                        {% endifequal %}
                    </a><a href="{% url 'axf:marketwidthparmas' categoryid=categoryid childcid=childcid order_rule=2 %}">
                        {% ifequal order_rule '2' %}
                            <button class="btn btn-default btn-success">价格最高</button>
                        {% else %}
                            <button class="btn btn-default">价格最高</button>

                        {% endifequal %}

                    </a>
                    </div>
                </div>
            </menu>
        </section>
    </div>
{% endblock %}