Myaxf/Myaxf/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('axf.urls', namespace='axf')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

Myaxf/axf/urls.py
from django.conf.urls import url

from axf import views








urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^market/', views.market, name='market'),
    url(r'^jsonmarket/', views.josn_market, name='jsonmarket'),
    url(r'^marketwidthparmas/(?P<categoryid>\d+)/(?P<childcid>\d+)/(?P<order_rule>\d+)/', views.market_width_parmas, name='marketwidthparmas'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^mine/', views.mine, name='mine'),
    url(r'^userregister/', views.user_register, name='userregister'),
    url(r'^userlogout/', views.user_logout, name='userlogout'),
    url(r'^checkuser/', views.check_user, name='checkuser'),
    url(r'^checkemal/', views.check_emal, name='checkemal'),
    url(r'^userlogin/', views.user_login, name='userlogin'),
    url(r'^addtocartinmarket/', views.add_to_cart_inmarket, name='addtocartinmarket'),
    url(r'^subtocartinmarket/', views.sub_to_cart_inmarket, name='subtocartinmarket'),
    url(r'^subtocart/', views.sub_to_cart, name='subtocart'),
    url(r'^addtocart/', views.add_to_cart, name='addtocart'),
    url(r'^changecartstatus/', views.change_cart_status, name='changecartstatus'),
    url(r'^changecartsstatus/', views.change_carts_status, name='changecartsstatus'),
    url(r'^makeorder/', views.make_order, name='makeorder'),
    url(r'^orderdetail/', views.order_detail, name='orderdetail'),
    url(r'^alipay/', views.alipay, name='alipay'),
    url(r'^activeuser/', views.active_user, name='activeuser'),
    url(r'^orderlist/', views.order_list, name='orderlist'),
    url(r'^changeorderstatus/', views.change_order_status, name='changeorderstatus'),

]

Myaxf/axf/models.py
import hashlib

from django.db import models

# Create your models here.
class Home(models.Model):
    img = models.CharField(max_length=200)
    name = models.CharField(max_length=32)
    trackid = models.IntegerField(default=1)
    class Meta:
        abstract = True

class HomeWheel(Home):

    class Meta:
        db_table = 'axf_wheel'

class HomeNav(Home):

    class Meta:
        db_table = 'axf_nav'

class HomeMustBuy(Home):

    class Meta:
        db_table = 'axf_mustbuy'

class HomeShop(Home):
    class Meta:
        db_table = 'axf_shop'
'''
(trackid,name,img,categoryid,brandname,img1,childcid1,productid1,longname1,price1,marketprice1,
img2,childcid2,productid2,longname2,price2,marketprice2,
img3,childcid3,productid3,longname3,price3,marketprice3)

'''
class HomeShow(Home):
    categoryid = models.IntegerField(default=1, verbose_name='分类id')

    brandname = models.CharField(max_length=32, verbose_name='类名字')

    img1 = models.CharField(max_length=200)

    childcid1 = models.IntegerField(default=1)

    productid1 = models.IntegerField(default=1)

    longname1 = models.CharField(max_length=128)

    price1 = models.FloatField(default=0)

    marketprice1 = models.FloatField(default=0)

    img2 = models.CharField(max_length=200)

    childcid2 = models.IntegerField(default=1)

    productid2 = models.IntegerField(default=1)

    longname2 = models.CharField(max_length=128)

    price2 = models.FloatField(default=0)

    marketprice2 = models.FloatField(default=0)

    img3 = models.CharField(max_length=200)

    childcid3 = models.IntegerField(default=1)

    productid3 = models.IntegerField(default=1)

    longname3 = models.CharField(max_length=128)

    price3 = models.FloatField(default=0)

    marketprice3 = models.FloatField(default=0)
    class Meta:
        db_table = 'axf_mainshow'


class Foodtype(models.Model):
    typeid = models.IntegerField(default=1)
    typename = models.CharField(max_length=16)
    childtypenames = models.CharField(max_length=200)
    typesort = models.IntegerField(default=1)

    class Meta:
        db_table = 'axf_foodtypes'



'''
insert into axf_goods
(pmdesc,specifics,
price,marketprice,categoryid,childcid,childcidname,dealerid,storenums,productnum) 
values(乐吧薯片鲜虾味50.0g",0,0,"50g",2.00,2.500000,103541,103543,"膨化食品","4858",200,4);


'''
class Goods(models.Model):
    productid = models.IntegerField(default=1)
    productimg = models.CharField(max_length=256)
    productname = models.CharField(max_length=128)
    productlongname = models.CharField(max_length=256)
    isxf = models.BooleanField(default=False)
    pmdesc = models.BooleanField(default=False)
    specifics = models.CharField(max_length=32)
    price = models.FloatField(default=1)
    marketprice = models.FloatField(default=2)
    categoryid = models.IntegerField(default=1)
    childcid = models.IntegerField(default=1)
    childcidname = models.CharField(max_length=128)
    dealerid = models.IntegerField(default=1)
    storenums = models.IntegerField(default=2)
    productnum = models.IntegerField(default=1)
    class Meta:
        db_table = 'axf_goods'

class UserModel(models.Model):
    u_name = models.CharField(max_length=16, unique=True)
    u_password = models.CharField(max_length=128)
    u_emal = models.CharField(max_length=64, unique=True)
    u_icon = models.ImageField(upload_to='icons')
    is_delete = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    def set_password(self,password):
        self.u_password=self.generate_hash(password)

    def generate_hash(self, password):
        sha = hashlib.sha512()
        sha.update(password.encode('utf-8'))

        return sha.hexdigest()

    def check_password(self, password):

        return self.u_password == self.generate_hash(password)

    class Meta:
        db_table = 'axf_user'

class CartModel(models.Model):
    c_goods_num = models.IntegerField(default=1)
    c_goods_select = models.BooleanField(default=True)
    c_goods = models.ForeignKey(Goods)
    c_user = models.ForeignKey(UserModel)

    class Meta:
        db_table = 'axf_cart'

class OrderModel(models.Model):
    o_user = models.ForeignKey(UserModel)

    o_status = models.IntegerField(default=0)
    o_time = models.DateTimeField(auto_now=True)
    o_price = models.FloatField(default=0)

    class Meta:
        db_table = 'axf_order'

class OrderGoods(models.Model):

    o_order = models.ForeignKey(OrderModel)
    o_goods = models.ForeignKey(Goods)
    o_goods_num = models.IntegerField(default=1)

    class Meta:
        db_table = 'axf_ordergoods'

Myaxf/templates/order/order_detail.html
{% extends 'base/base_order.html' %}
{% load static %}
{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/oredr/css/ordel_detail.css' %}">
{% endblock %}

{% block extJS %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/oredr/js/order_detail.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="order_info">
            <p class="order_num">订单编号:{{ order.id }}</p>
            <ul>
                {% for ordergoods in order.ordergoods_set.all %}
                    <li>
                        <a href="#">
                            <img src="{{ ordergoods.o_goods.productimg }}">
                            <div class="shoppingInfo">
                                <h6>{{ ordergoods.o_goods.productlongname }}</h6>

                                <p class="unit">{{ ordergoods.o_goods.specifics }}</p>
                                <p class="price"><span>￥{{ ordergoods.o_goods.price }}</span></p>
                            </div>
                        </a>
                    </li>

                {% endfor %}
                <p class="total_price">总价：{{ order.o_price }}</p>
                <button orderid="{{ order.id }}" id="alipay" class="btn btn-success btn-block">支付</button>

            </ul>
        </div>
    </div>
{% endblock %}

Myaxf/templates/order/order_list.html
{% extends 'base/base_user.html' %}
{% load static %}
{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/oredr/css/order_list.css' %}">
{% endblock %}
{% block extJS %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/oredr/js/order_list.js' %}"></script>
{% endblock %}
{% block content %}
    <div class="container">
        {% ifequal status '0' %}
            {% ifequal orderlist.exists 0 %}
                <span>您还没有下单</span>

            {% endifequal %}

            <ul>
                {% for order in orderlist %}

                    <li>
                        <div class="order_info">
                            <a href="{% url 'axf:orderdetail' %}?order_id={{ order.id }}">
                                <p class="order_num">订单编号:{{ order.id }}</p>
                            </a>
                            <ul>
                                {% for ordergoods in order.ordergoods_set.all %}

                                    <li>

                                        <a href="#">
                                            <img src="{{ ordergoods.o_goods.productimg }}">
                                            <div class="shoppingInfo">
                                                <h6>{{ ordergoods.o_goods.productlongname }}</h6>

                                                <p class="unit">{{ ordergoods.o_goods.specifics }}</p>
                                                <p class="price">
                                                    <span>￥{{ ordergoods.o_goods.price }}</span>
                                                </p>
                                            </div>
                                        </a>

                                    </li>

                                {% endfor %}

                            </ul>
                        </div>
                    </li>

                {% endfor %}
            </ul>
        {% endifequal %}
        {% ifequal status '1' %}
            <ul>
                {% for order in orderlist %}

                    <li>
                        <div class="order_info">
                                <p class="order_num">订单编号:{{ order.id }}</p>
                            <ul>
                                {% for ordergoods in order.ordergoods_set.all %}

                                    <li>

                                        <a href="#">
                                            <img src="{{ ordergoods.o_goods.productimg }}">
                                            <div class="shoppingInfo">
                                                <h6>{{ ordergoods.o_goods.productlongname }}</h6>

                                                <p class="unit">{{ ordergoods.o_goods.specifics }}</p>
                                                <p class="price">
                                                    <span>￥{{ ordergoods.o_goods.price }}</span>
                                                </p>
                                            </div>
                                        </a>

                                    </li>

                                {% endfor %}
                                <span class="affirm_receipt">确认收货</span>

                            </ul>
                        </div>
                    </li>

                {% endfor %}
            </ul>

        {% endifequal %}


    </div>

{% endblock %}